### ISSUE TITLE
Error converting many datasets

### ISSUE THREAD

**Issue by nakumgaurav** [hu-ner/huner#17]
I am facing errors converting most of the datasets. For instance, JNLPBA gives the following error:

`Converting JNLPBA
Traceback (most recent call last):
  File "scripts/jnlpba_to_conll.py", line 25, in <module>
    f_in.__next__()
AttributeError: 'file' object has no attribute '__next__'
Traceback (most recent call last):
  File "scripts/jnlpba_to_conll.py", line 25, in <module>
    f_in.__next__()
AttributeError: 'file' object has no attribute '__next__'`

It would be nice if you could fix the docker version of convert_corpora. Thanks!

**Comment by leonweber** [comment]
Hey @nakumgaurav thanks for reporting the issues. There were two major sources of errors: the container used python2 instead of python3 and the default encoding was ascii. Both of them should be fixed on the https://github.com/hu-ner/huner/tree/docker_for_ner_scripts branch now. 

Please report any further corpora-specific issues with the conversion scripts in https://github.com/hu-ner/huner/issues/14 

I will close this issue to unify reporting of problems with the conversion.
