### ISSUE TITLE
How to make sure that there is no overlapping between train set, dev set and test set?

### ISSUE THREAD

**Issue by liangpingding** [hu-ner/huner#28]
Hi, I saw HUNER paper and I'm interested in the dataset split method that you uesd. You mentioned in the paper that 

> "To avoid knowledge leaks in the gold standard settings, we adjusted the splits in such a way that there is no overlap between the train, development and test splits across corpora for the same entity type. That is, we ensure that a sentence is contained either only in the train or development or test portion of all corpora, even when it is contained by multiple corpora. This is especially important, as some corpora are based on the same documents."

I'm wondering when combining the corresponding corpora for each entity type, is it guranteed that no duplicates and no overlapping between dataset splits? Did you do that when you split each corpora according to the split id? Because I didn't find the corresponding code for concatenating all the corpora after dataset split for each entity type

**Comment by leonweber** [comment]
Hi, thank you for your interest in HUNER. 

> I'm wondering when combining the corresponding corpora for each entity type, is it guranteed that no duplicates and no overlapping between dataset splits?

We only ensured no overlap between dataset splits. There can be duplicates within one split however.

> Did you do that when you split each corpora according to the split id?

Yes, this is encoded in the split ids. They are chosen so that there won't be any overlap.

> Because I didn't find the corresponding code for concatenating all the corpora after dataset split for each entity type

For HUNER, we did this manually. I would strongly suggest to use HUNER's successor [HunFlair]( https://academic.oup.com/bioinformatics/article/37/17/2792/6122692?login=false), both for dataset access and for tagging, because it is much more user-friendly. You can find a tutorial on how to concatenate all corpora for an entity type [here](https://github.com/flairNLP/flair/blob/master/resources/docs/HUNFLAIR_TUTORIAL_2_TRAINING.md#training-hunflair-from-scratch).

**Comment by liangpingding** [comment]
Hi, thanks for your quick response. All good and clear. Actually I'm using Hunflair right now. And I found that there is a difference between Huner and HunFlair for the corpora processing. In HunFlair, they don't use Biosemantics corpora [https://github.com/flairNLP/flair/blob/master/resources/docs/HUNFLAIR_EXPERIMENTS.md](url) and I don't know why they miss this one. So I'm wondering if I should still use Biosemantics corpora.

**Comment by leonweber** [comment]
We discuss the omission in [HunFlair's supplement](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/37/17/10.1093_bioinformatics_btab042/1/btab042_supplementary_data.pdf?Expires=1666103120&Signature=YoB21vNmn9QEoMcwsn6Ykiu~ibcWlpIKNOknTVvU-u9lAdunwWs0IMVMLb~LV8MU8fksTfPpswM~qpkNErWggNtVS2LO7qDjnoT8jWiv7vbr57OoDov68FZGTTYm8cSmkz24P85FF-tBT~sbW90LFuHjF3IDi4vWT~FtyiGqZvFKN14ibtSlnyHK5oq0VJjoHSxXg9~7QlQ8~nQwOelqzb8~MugzzVyugWWuSpfR-RQG7ZavOcqGj3-ji1zXopkUGMdJOyfKwxulaluxH1qCXAJpmZZAwwjdy7yTCXY9UX9p8vqAFquQgUuU70kPT-D1fD9E~A~rx3ZhPCbzQRhOcw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA). Basically, we found some data quality issues with the corpus (it includes very long sentences) and including it into the training mix didn't improve results.

**Comment by liangpingding** [comment]
Thanks for your repley!
